#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<sys/socket.h>
#include<netinet/in.h>
#include<netdb.h>
#include<errno.h>
#include<signal.h>
#include<unistd.h>
#include<string.h>
#include<arpa/inet.h>
#include<sys/wait.h>
#include<fcntl.h>
#include<netinet/in.h>
#include<sys/stat.h>
#include<errno.h>
#include<time.h>
#include<pthread.h>
#include<dirent.h>

